image: node:alpine

stages:
  - build
  - test

Test:
  stage: test
  tags:
    - local
  before_script: 
     - yarn install
   script:
     - npm run test

Build:
  stage: build
  tags:
    - local
  before_script:
    - yarn install
  script:
    - npm run build



