image: node:alpine

stages:
  - build
  - test

Build:
  stage: build
  before_script:
    - npm install
  script:
    - npm run build

Test:
  stage: test
  before_script: 
    - npm install
  script:
    - npm run test

