image: node:alpine

stages:
  - deploy
  - test
  
Build:
  stage: deploy
  tags:
    - local
  before_script:
    - yarn install
  only:
   - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
  script:
    - yarn build
    - echo $NPM_TOKEN
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN">.npmrc
    - cat .npmrc
    - echo $CI_COMMIT_TAG
    - yarn publish --tag $CI_COMMIT_TAG --access public

Test:
  stage: test
  tags:
    - local
  before_script: 
    - yarn install
  script:
    - yarn test



