image: node:alpine

stages:
  - test
  - deploy

Test:
  stage: test
  tags:
    - local
  before_script: 
    - yarn install
  script:
    - yarn test

Build:
  stage: deploy
  tags:
    - local
  before_script:
    - yarn install
  script:
    - yarn build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - yarn publish --tag 0.0.6

