image: node:alpine

stages:
  - deploy
  - test

before_script: 
  - yarn install  

Build:
  stage: deploy
  tags:
    - local
  only:
   - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
  before_script: 
    - echo $GITHUB_ACTOR
    - git switch -c master
    - git config user.email "$GITHUB_ACTOR@gmail.com"
    - git config user.name "$GITHUB_ACTOR"
    - npm config set git-tag-version=false
    
  script:
    - npm version patch
    - yarn build
    - echo $NPM_TOKEN
    - echo version
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN">.npmrc
    - cat .npmrc
    - echo $CI_COMMIT_TAG
    - yarn publish --tag latest --access public

Test:
  stage: test
  tags:
    - local
  script:
    - yarn test



