image: node:9.4.0

cache:
  paths:
    - node_modules/
    - .yarn

before_script:
  - apt-get update -qq && apt-get install

stages:
  - build
  - test

Build:
  stage: build
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install 
  script:
    - npm run build

Test:
  stage: test
  before_script: 
    - yarn config set cache-folder .yarn
    - yarn install 
  script:
    -npm run test

