image: node:alpine

stages:
  - build
  - test

Build:
  stage: build
  tags:
    - local
  before_script:
    - yarn install
  script:
    - yarn build

Test:
  stage: test
  tags:
    - local
  before_script: 
    - yarn install
  script:
    - yarn test

