image: node:alpine

stages:
  - test
  - deploy

Test:
  stage: test
  tags:
    - local
  before_script: 
    - yarn install
  script:
    - yarn test

Build:
  stage: deploy
  tags:
    - local
  before_script:
    - yarn install
  script:
    - yarn build
    - echo '//registry.npmjs.org/:_authToken=26f92322-f725-4f06-96b2-a816f5e3956b'>.npmrc
    - yarn publish --tag 0.0.8

