image: node:alpine

stages:
  - deploy
  - test

before_script: 
  - yarn install  

Build:
  stage: deploy
  tags:
    - local
  only:
   - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
  before_script: 
    - npm config set git-tag-version=false
    - npm version patch
  script:
    - yarn build
    - echo $NPM_TOKEN
    - echo version
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN">.npmrc
    - cat .npmrc
    - echo $CI_COMMIT_TAG
    - yarn publish --tag latest --access public

Test:
  stage: test
  tags:
    - local
  script:
    - yarn test



