image: docker:latest

before_script:
  - docker info
  - apt-get update -qq && apt-get install

stages:
  - build
  - test

Build:
  stage: build
  tags: 
    -node
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - yarn config set cache-folder .yarn
    - yarn install 
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
    - npm run build

Test:
  stage:test
  tags:
    - node
  before_script: 
    - yarn config set cache-folder .yarn
    - yarn install 
  script:
    -npm run test

