image: node:alpine

stages:
  - test
  - build

Test:
  stage: test
  tags:
    - local
  before_script: 
    - yarn install
  script:
    - yarn test

Build:
  stage: build
  tags:
    - local
  before_script:
    - yarn install
  script:
    - yarn publish



